# Performance comparison during the COVID-19 pandemic of two portfolios composed by the five highests and lowests beta coefficients stocks present in the Ibovespa index

#### João Vitor de Paiva Marcotti
#### Electrical Engineer - State University of Maringá - UEM (Brazil)
#### 8th Semester Economics Student - Cesumar University - UniCesumar (Brazil)
#### Open to Work
#### Contact: joaovmarcotti@hotmail.com

# ---------------------------------------------------------------------------------------------------------------

In [1]:
# Importando as bibliotecas
# Importing the libraries
import numpy as np
import pandas as pd
import yfinance as yfin
import pandas_datareader as pdr
import matplotlib.pyplot as plt

In [2]:
# Seleciona as ações que farão parte dos portfolios simulados, neste caso são as ações que compõem o índice Bovespa
# Select the stocks that will be part of the simulated portfolios, in this case the stocks are part of the Bovespa Index

stocks = ['^BVSP','ABEV3.SA','AZUL4.SA','AMER3.SA','B3SA3.SA','BBSE3.SA','BBDC3.SA','BBDC4.SA','BRAP4.SA',
          'BBAS3.SA','BRKM3.SA','BRFS3.SA','BPAC11.SA','CRFB3.SA','CCRO3.SA','CMIG4.SA','CIEL3.SA',
          'COGN3.SA','CSAN3.SA','CVCB3.SA','CYRE3.SA','ECOR3.SA','ELET3.SA','ELET6.SA','EMBR3.SA','ENBR3.SA','EGIE3.SA',
          'EQTL3.SA','FLRY3.SA','GGBR4.SA','GOAU4.SA','GOLL4.SA','NTCO3.SA','HAPV3.SA','HYPE3.SA','HAPV3.SA',
          'IRBR3.SA','ITSA4.SA','ITUB4.SA','JBSS3.SA','KLBN11.SA','RENT3.SA','LREN3.SA','MGLU3.SA','MRFG3.SA',
          'MRVE3.SA','MULT3.SA','PCAR3.SA','PETR3.SA','PETR4.SA','VBBR3.SA','QUAL3.SA','RADL3.SA','RAIL3.SA','SBSP3.SA',
          'SANB11.SA','CSNA3.SA','SUZB3.SA','TAEE11.SA','VIVT3.SA','TIMS3.SA','TOTS3.SA',
          'UGPA3.SA','USIM5.SA','VALE3.SA','VIIA3.SA','WEGE3.SA','YDUQ3.SA']

# Importa dados entre os anos de 2015 e 2020 para a estimativa do coeficiente beta
# Import data between the years 2015 and 2020 to estimate the beta coefficient

data = yfin.download(stocks, start='2018-01-01', end="2020-01-01")['Close']

[*********************100%***********************]  67 of 67 completed

# ---------------------------------------------------------------------------------------------------------------

# Data Cleaning

In [3]:
# Ordena os valores de fechamento das ações por data
# Order stock closing values by date

data = data.sort_values(by=['Date'])
data

,ABEV3.SA,AMER3.SA,AZUL4.SA,B3SA3.SA,BBAS3.SA,BBDC3.SA,BBDC4.SA,BBSE3.SA,BPAC11.SA,BRAP4.SA,...,TOTS3.SA,UGPA3.SA,USIM5.SA,VALE3.SA,VBBR3.SA,VIIA3.SA,VIVT3.SA,WEGE3.SA,YDUQ3.SA,^BVSP
Date,,,,,,,,,,,,,,,,,,,,,
2018-01-02,21.690001,19.768276,27.150000,7.636666,32.930000,18.373060,19.693554,28.700001,4.725000,26.223991,...,10.030941,38.485001,9.60,41.720001,NaN,7.71,41.400002,9.623076,33.869999,77891.0
2018-01-03,21.740000,19.610130,27.059999,7.766666,33.349998,18.441362,19.773239,28.719999,4.770000,26.471889,...,10.243869,38.105000,9.92,41.470001,NaN,7.75,40.200001,9.476923,33.900002,77995.0
2018-01-04,21.620001,20.143873,27.230000,7.816666,33.669998,18.777178,20.097670,28.780001,4.787500,27.224436,...,10.180656,38.549999,10.48,41.639999,NaN,7.81,40.639999,9.384615,33.759998,78647.0
2018-01-05,21.700001,19.768276,27.200001,7.930000,33.669998,18.782869,20.211506,28.969999,4.692500,27.879593,...,10.400239,38.630001,10.03,42.290001,NaN,7.56,40.740002,9.423076,33.299999,79071.0
2018-01-08,21.660000,19.610130,26.910000,7.966666,33.750000,18.782869,20.205814,29.139999,4.750000,28.366533,...,10.393585,38.900002,10.14,43.230000,NaN,7.69,41.169998,9.500000,33.419998,79379.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-20,18.910000,62.700001,57.000000,16.366667,51.060001,25.033810,26.814425,37.740002,18.892500,33.545815,...,22.820000,24.610001,9.33,54.790001,29.299999,11.37,48.849998,16.945000,48.119999,115121.0
2019-12-23,18.959999,62.599998,57.599998,15.623333,52.599998,25.537189,26.979713,37.950001,18.542500,34.023903,...,22.556665,25.330000,9.53,54.580002,30.200001,11.67,49.000000,16.895000,49.000000,115863.0
2019-12-26,19.219999,62.730000,57.070000,15.550000,53.200001,25.807663,27.317806,37.759998,18.912500,34.572819,...,22.330000,25.600000,9.53,54.790001,30.139999,11.80,49.889999,17.424999,48.599998,117203.0
2019-12-27,19.160000,62.400002,57.799999,14.736666,52.970001,25.642374,27.212622,37.840000,18.684999,34.679062,...,21.606667,25.719999,9.43,53.599998,30.430000,11.50,49.330002,17.670000,48.799999,116534.0
2019-12-30,18.670000,62.860001,58.279999,14.323333,52.820000,25.597296,27.175056,37.700001,18.900000,33.891102,...,21.516666,25.480000,9.51,53.299999,30.070000,11.17,49.040001,17.330000,47.500000,115964.0

In [4]:
nan_counts = data.isna().sum()
nan_counts = nan_counts[nan_counts > 0]
nan_counts

HAPV3.SA     79
NTCO3.SA    487
VBBR3.SA     49
^BVSP         1
dtype: int64

In [5]:
data = data.drop(['NTCO3.SA'],axis=1)
data

,ABEV3.SA,AMER3.SA,AZUL4.SA,B3SA3.SA,BBAS3.SA,BBDC3.SA,BBDC4.SA,BBSE3.SA,BPAC11.SA,BRAP4.SA,...,TOTS3.SA,UGPA3.SA,USIM5.SA,VALE3.SA,VBBR3.SA,VIIA3.SA,VIVT3.SA,WEGE3.SA,YDUQ3.SA,^BVSP
Date,,,,,,,,,,,,,,,,,,,,,
2018-01-02,21.690001,19.768276,27.150000,7.636666,32.930000,18.373060,19.693554,28.700001,4.725000,26.223991,...,10.030941,38.485001,9.60,41.720001,NaN,7.71,41.400002,9.623076,33.869999,77891.0
2018-01-03,21.740000,19.610130,27.059999,7.766666,33.349998,18.441362,19.773239,28.719999,4.770000,26.471889,...,10.243869,38.105000,9.92,41.470001,NaN,7.75,40.200001,9.476923,33.900002,77995.0
2018-01-04,21.620001,20.143873,27.230000,7.816666,33.669998,18.777178,20.097670,28.780001,4.787500,27.224436,...,10.180656,38.549999,10.48,41.639999,NaN,7.81,40.639999,9.384615,33.759998,78647.0
2018-01-05,21.700001,19.768276,27.200001,7.930000,33.669998,18.782869,20.211506,28.969999,4.692500,27.879593,...,10.400239,38.630001,10.03,42.290001,NaN,7.56,40.740002,9.423076,33.299999,79071.0
2018-01-08,21.660000,19.610130,26.910000,7.966666,33.750000,18.782869,20.205814,29.139999,4.750000,28.366533,...,10.393585,38.900002,10.14,43.230000,NaN,7.69,41.169998,9.500000,33.419998,79379.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-20,18.910000,62.700001,57.000000,16.366667,51.060001,25.033810,26.814425,37.740002,18.892500,33.545815,...,22.820000,24.610001,9.33,54.790001,29.299999,11.37,48.849998,16.945000,48.119999,115121.0
2019-12-23,18.959999,62.599998,57.599998,15.623333,52.599998,25.537189,26.979713,37.950001,18.542500,34.023903,...,22.556665,25.330000,9.53,54.580002,30.200001,11.67,49.000000,16.895000,49.000000,115863.0
2019-12-26,19.219999,62.730000,57.070000,15.550000,53.200001,25.807663,27.317806,37.759998,18.912500,34.572819,...,22.330000,25.600000,9.53,54.790001,30.139999,11.80,49.889999,17.424999,48.599998,117203.0
2019-12-27,19.160000,62.400002,57.799999,14.736666,52.970001,25.642374,27.212622,37.840000,18.684999,34.679062,...,21.606667,25.719999,9.43,53.599998,30.430000,11.50,49.330002,17.670000,48.799999,116534.0
2019-12-30,18.670000,62.860001,58.279999,14.323333,52.820000,25.597296,27.175056,37.700001,18.900000,33.891102,...,21.516666,25.480000,9.51,53.299999,30.070000,11.17,49.040001,17.330000,47.500000,115964.0

In [6]:
# Calcula a varição diária de cada ação
# Calculate the daily variation of each stock

daily_variation = (data-data.shift(1))/data.shift(1)
daily_variation

,ABEV3.SA,AMER3.SA,AZUL4.SA,B3SA3.SA,BBAS3.SA,BBDC3.SA,BBDC4.SA,BBSE3.SA,BPAC11.SA,BRAP4.SA,...,TOTS3.SA,UGPA3.SA,USIM5.SA,VALE3.SA,VBBR3.SA,VIIA3.SA,VIVT3.SA,WEGE3.SA,YDUQ3.SA,^BVSP
Date,,,,,,,,,,,,,,,,,,,,,
2018-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018-01-03,0.002305,-0.008000,-0.003315,0.017023,0.012754,0.003718,0.004046,0.000697,0.009524,0.009453,...,0.021227,-0.009874,0.033333,-0.005992,NaN,0.005188,-0.028986,-0.015188,0.000886,0.001335
2018-01-04,-0.005520,0.027218,0.006282,0.006438,0.009595,0.018210,0.016408,0.002089,0.003669,0.028428,...,-0.006171,0.011678,0.056452,0.004099,NaN,0.007742,0.010945,-0.009740,-0.004130,0.008360
2018-01-05,0.003700,-0.018646,-0.001102,0.014499,0.000000,0.000303,0.005664,0.006602,-0.019843,0.024065,...,0.021569,0.002075,-0.042939,0.015610,NaN,-0.032010,0.002461,0.004098,-0.013626,0.005391
2018-01-08,-0.001843,-0.008000,-0.010662,0.004624,0.002376,0.000000,-0.000282,0.005868,0.012254,0.017466,...,-0.000640,0.006989,0.010967,0.022227,NaN,0.017196,0.010555,0.008163,0.003604,0.003895
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-20,-0.013563,-0.017395,-0.012303,0.011120,-0.001955,-0.028571,-0.020850,-0.014621,-0.005265,0.010400,...,0.006765,0.013174,0.001073,0.014630,-0.004417,0.011566,0.020899,0.008631,-0.031791,-0.000087
2019-12-23,0.002644,-0.001595,0.010526,-0.045418,0.030161,0.020108,0.006164,0.005564,-0.018526,0.014252,...,-0.011540,0.029256,0.021436,-0.003833,0.030717,0.026385,0.003071,-0.002951,0.018288,0.006445
2019-12-26,0.013713,0.002077,-0.009201,-0.004694,0.011407,0.010591,0.012531,-0.005007,0.019954,0.016133,...,-0.010049,0.010659,0.000000,0.003848,-0.001987,0.011140,0.018163,0.031370,-0.008163,0.011565
2019-12-27,-0.003122,-0.005261,0.012791,-0.052304,-0.004323,-0.006405,-0.003850,0.002119,-0.012029,0.003073,...,-0.032393,0.004687,-0.010493,-0.021719,0.009622,-0.025424,-0.011225,0.014060,0.004115,-0.005708
2019-12-30,-0.025574,0.007372,0.008304,-0.028048,-0.002832,-0.001758,-0.001380,-0.003700,0.011507,-0.022721,...,-0.004165,-0.009331,0.008484,-0.005597,-0.011830,-0.028696,-0.005879,-0.019242,-0.026639,-0.004891

In [7]:
daily_variation = daily_variation.dropna()
daily_variation

,ABEV3.SA,AMER3.SA,AZUL4.SA,B3SA3.SA,BBAS3.SA,BBDC3.SA,BBDC4.SA,BBSE3.SA,BPAC11.SA,BRAP4.SA,...,TOTS3.SA,UGPA3.SA,USIM5.SA,VALE3.SA,VBBR3.SA,VIIA3.SA,VIVT3.SA,WEGE3.SA,YDUQ3.SA,^BVSP
Date,,,,,,,,,,,,,,,,,,,,,
2018-04-27,-0.005577,-0.012558,0.030859,0.006233,0.000000,0.002465,0.010941,0.005382,0.001330,-0.007351,...,0.001249,0.006823,-0.026340,-0.007187,0.026697,0.027228,0.007534,0.000558,-0.051108,0.000718
2018-04-30,0.006471,-0.032798,0.027958,-0.020519,-0.017403,-0.019367,-0.015380,-0.019272,-0.008857,-0.024685,...,-0.001872,-0.024685,0.016791,0.006618,0.011899,-0.022892,-0.000680,-0.008366,-0.006849,-0.003817
2018-05-02,-0.028290,-0.039100,-0.024451,-0.027273,-0.018529,-0.015987,-0.025745,0.000000,-0.025916,-0.003937,...,-0.026562,-0.005459,-0.006422,0.000822,0.006098,-0.001233,0.005442,0.012936,-0.027900,-0.018208
2018-05-03,-0.003088,-0.005402,-0.048719,-0.018285,-0.028318,-0.012424,-0.021081,-0.001456,-0.022477,0.007905,...,-0.000321,-0.101630,-0.022161,0.007801,-0.031602,-0.060494,-0.038566,-0.022765,-0.000322,-0.014891
2018-05-04,-0.004425,0.044171,-0.008881,-0.004967,-0.002000,-0.003548,0.000910,-0.013848,-0.005162,0.014286,...,0.000321,-0.000185,0.036827,0.012426,-0.022351,-0.006570,-0.001877,-0.022727,0.006452,-0.002041
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-20,-0.013563,-0.017395,-0.012303,0.011120,-0.001955,-0.028571,-0.020850,-0.014621,-0.005265,0.010400,...,0.006765,0.013174,0.001073,0.014630,-0.004417,0.011566,0.020899,0.008631,-0.031791,-0.000087
2019-12-23,0.002644,-0.001595,0.010526,-0.045418,0.030161,0.020108,0.006164,0.005564,-0.018526,0.014252,...,-0.011540,0.029256,0.021436,-0.003833,0.030717,0.026385,0.003071,-0.002951,0.018288,0.006445
2019-12-26,0.013713,0.002077,-0.009201,-0.004694,0.011407,0.010591,0.012531,-0.005007,0.019954,0.016133,...,-0.010049,0.010659,0.000000,0.003848,-0.001987,0.011140,0.018163,0.031370,-0.008163,0.011565
2019-12-27,-0.003122,-0.005261,0.012791,-0.052304,-0.004323,-0.006405,-0.003850,0.002119,-0.012029,0.003073,...,-0.032393,0.004687,-0.010493,-0.021719,0.009622,-0.025424,-0.011225,0.014060,0.004115,-0.005708
2019-12-30,-0.025574,0.007372,0.008304,-0.028048,-0.002832,-0.001758,-0.001380,-0.003700,0.011507,-0.022721,...,-0.004165,-0.009331,0.008484,-0.005597,-0.011830,-0.028696,-0.005879,-0.019242,-0.026639,-0.004891

# ---------------------------------------------------------------------------------------------------------------

# Calculating the Beta Coefficient

In [8]:
# Retorna a covariância entre as variações diárias das ações
# Return the covariance between the stock's daily variations

daily_variation_covariance = daily_variation.cov()*250

# Retorna a covariância entre cada ação e o Ibovespa
# Returns the covariance between each stock and the Ibovespa

daily_variation_covariance['^BVSP']

ABEV3.SA    0.023422
AMER3.SA    0.060584
AZUL4.SA    0.050086
B3SA3.SA    0.051672
BBAS3.SA    0.059790
              ...
VIIA3.SA    0.052241
VIVT3.SA    0.020856
WEGE3.SA    0.027172
YDUQ3.SA    0.046911
^BVSP       0.041653
Name: ^BVSP, Length: 66, dtype: float64

In [9]:
# Retorna a variância das variações diárias de cada ação
# Returns the variance of the daily variation of each stock

daily_variation_variance = daily_variation.var()*250

# Retorna a variãncia do Ibovespa
# Returns the Ibovespa variance

daily_variation_variance['VBBR3.SA']

0.16378719246111748

In [10]:
# Calcula o coeficiente beta de cada ação
# Calculates the beta coeficient of each stock

beta = daily_variation_covariance['^BVSP']/daily_variation_variance['^BVSP']
beta['VBBR3.SA']

0.9891274079622672

# ---------------------------------------------------------------------------------------------------------------

# Lowest and Highest Beta Stocks

In [11]:
# Ordena os coeficientes beta calculados do menor para o maior, exibindo os 5 menores coeficientes beta
# Orders calculated beta coeficients from lowest to highest, displaying the 5 lowest beta coeficient

lowests_beta = beta.sort_values(na_position='last').head()
lowests_beta

PCAR3.SA     0.010326
SUZB3.SA     0.074875
KLBN11.SA    0.353248
IRBR3.SA     0.382392
BRKM3.SA     0.411891
Name: ^BVSP, dtype: float64

In [12]:
# Ordena os betas calculados do maior para o menor, exibindo os 5 maiores beta coeficients
# Orders calculated betas from largest to smallest, displaying the 5 highests beta coeficients

highests_beta = beta.sort_values(na_position='first').tail()
highests_beta

AMER3.SA    1.454499
PETR4.SA    1.515880
ELET6.SA    1.586512
GOLL4.SA    1.697122
ELET3.SA    1.704224
Name: ^BVSP, dtype: float64

In [13]:
# Define pesos iguais para cada ação: 20%
# Sets equal weights for each stock: 20%

weights = [0.2,0.2,0.2,0.2,0.2]

# Transforma a lista 'weights' em um vetor numpy
# Turns the list 'weights' into a numpy array

weights = np.asarray(weights)

# ---------------------------------------------------------------------------------------------------------------

# Biggest Stocks Fall Period (02/21/2020 - 03/21/2020)

# ---------------------------------------------------------------------------------------------------------------

 # Lowests Beta Portfolio Volatility

In [14]:
# Seleciona as cinco ações de menor beta
# Select the five slowests beta stocks

lowests_beta_stocks = lowests_beta.index.tolist()

# Importa dados referentes ao período da maior queda do Ibovespa em razão da Pandemia de Covid-19
# Import data referring to the period of the biggest drop in the Ibovespa due to the Covid-19 Pandemic

return_lowests = yfin.download(lowests_beta_stocks, start='2020-02-21', end="2020-03-21")['Close']
return_lowests

[*********************100%***********************]  5 of 5 completed

             BRKM3.SA    IRBR3.SA  KLBN11.SA   PCAR3.SA   SUZB3.SA
Date
2020-02-21  33.360001  748.050354  22.020000  88.160004  41.419998
2020-02-26  30.440001  736.088928  20.139999  88.160004  38.599998
2020-02-27  31.780001  785.084839  19.900000  82.000000  38.130001
2020-02-28  31.000000  764.842407  19.330000  82.000000  38.139999
2020-03-02  32.500000  698.134338  20.430000  73.730003  39.650002
2020-03-03  32.549999  644.077820  20.750000  74.629997  39.939999
2020-03-04  33.200001  438.202911  22.090000  74.500000  43.540001
2020-03-05  31.209999  367.354370  21.719999  71.089996  42.619999
2020-03-06  29.900000  376.555481  21.280001  69.309998  40.029999
2020-03-09  26.770000  316.518219  19.590000  65.300003  37.950001
2020-03-10  29.080000  315.138062  19.709999  66.500000  38.860001
2020-03-11  26.500000  292.135284  18.200001  62.400002  35.459999
2020-03-12  22.000000  210.475418  15.800000  57.689999  29.740000
2020-03-13  23.260000  230.027786  16.160000  65.500000  31.580000
2020-03-16  23.090000  201.274307  13.700000  62.369999  28.370001
2020-03-17  24.100000  203.574585  14.280000  68.000000  28.000000
2020-03-18  18.600000  165.620010  12.810000  59.869999  24.620001
2020-03-19  16.610001  174.591080  14.080000  64.459999  27.330000
2020-03-20  16.600000  167.920288  13.050000  67.230003  27.389999

In [15]:
# Calcula a varição diária de cada ação
# Calculate the daily variation of each stock

daily_variation_lowests = (return_lowests-return_lowests.shift(1))/return_lowests.shift(1)
daily_variation_lowests

            BRKM3.SA  IRBR3.SA  KLBN11.SA  PCAR3.SA  SUZB3.SA
Date
2020-02-21       NaN       NaN        NaN       NaN       NaN
2020-02-26 -0.087530 -0.015990  -0.085377  0.000000 -0.068083
2020-02-27  0.044021  0.066562  -0.011917 -0.069873 -0.012176
2020-02-28 -0.024544 -0.025784  -0.028643  0.000000  0.000262
2020-03-02  0.048387 -0.087218   0.056906 -0.100854  0.039591
2020-03-03  0.001538 -0.077430   0.015663  0.012207  0.007314
2020-03-04  0.019969 -0.319643   0.064578 -0.001742  0.090135
2020-03-05 -0.059940 -0.161680  -0.016750 -0.045772 -0.021130
2020-03-06 -0.041974  0.025047  -0.020258 -0.025039 -0.060770
2020-03-09 -0.104682 -0.159438  -0.079417 -0.057856 -0.051961
2020-03-10  0.086291 -0.004360   0.006126  0.018377  0.023979
2020-03-11 -0.088721 -0.072993  -0.076611 -0.061654 -0.087494
2020-03-12 -0.169811 -0.279528  -0.131868 -0.075481 -0.161309
2020-03-13  0.057273  0.092896   0.022785  0.135379  0.061870
2020-03-16 -0.007309 -0.125000  -0.152228 -0.047786 -0.101647
2020-03-17  0.043742  0.011429   0.042336  0.090268 -0.013042
2020-03-18 -0.228216 -0.186441  -0.102941 -0.119559 -0.120714
2020-03-19 -0.106989  0.054167   0.099141  0.076666  0.110073
2020-03-20 -0.000602 -0.038208  -0.073153  0.042972  0.002195

In [16]:
# Calcula a variância das ações de menor coeficiente beta
# Calculates the variance of the smallest beta stocks

covariance_lowests = daily_variation_lowests.cov()

# Calcula a volatilidade das ações de menor beta
# Calculates the volatility of the smallest beta stocks

volatility_lowests = np.sqrt(np.dot(weights.T,np.dot(covariance_lowests,weights)))
volatility_lowests

0.06400450946881654

# ---------------------------------------------------------------------------------------------------------------

 # Lowests Beta Portfolio Return

In [17]:
# Obtém a variação total do valor das ações neste intervalo de tempo
# Gets the total variation of the stocks' value in this time interval

total_variation_lowests = (return_lowests.iloc[-1]-return_lowests.iloc[0])/return_lowests.iloc[0]
total_variation_lowests

BRKM3.SA    -0.502398
IRBR3.SA    -0.775523
KLBN11.SA   -0.407357
PCAR3.SA    -0.237409
SUZB3.SA    -0.338725
dtype: float64

In [18]:
# Exibe a variação total do valor, os pesos das ações e seus tickets em uma tabela
# Displays total value variation, stock weights and their tickets in a table

portfolio_lowests = pd.DataFrame({'Weight':weights,'Return':total_variation_lowests})
portfolio_lowests

           Weight    Return
BRKM3.SA      0.2 -0.502398
IRBR3.SA      0.2 -0.775523
KLBN11.SA     0.2 -0.407357
PCAR3.SA      0.2 -0.237409
SUZB3.SA      0.2 -0.338725

In [19]:
# Calcula o retorno médio das ações, ou seja, o retorno da carteira formada por elas
# Calculates the average return of the stocks (the return of the portfolio composted by them)

average_total_return_lowests = total_variation_lowests.mean()
average_total_return_lowests

-0.45228245344861084

# ---------------------------------------------------------------------------------------------------------------

 # Highests Beta Portfolio Volatility

In [20]:
# Seleciona as cinco ações de menor beta
# Select the five slowests beta stocks

highests_beta_stocks = highests_beta.index.tolist()

# Importa dados referentes ao período da maior queda do Ibovespa em razão da Pandemia de Covid-19
# Import data referring to the period of the biggest drop in the Ibovespa due to the Covid-19 Pandemic

return_highests = yfin.download(highests_beta_stocks, start='2020-02-21', end="2020-03-21")['Close']
return_highests

[*********************100%***********************]  5 of 5 completed

             AMER3.SA   ELET3.SA   ELET6.SA   GOLL4.SA   PETR4.SA
Date
2020-02-21  72.514824  37.660000  39.730000  33.820000  29.139999
2020-02-26  65.458687  34.150002  36.990002  28.980000  26.209999
2020-02-27  62.498692  33.500000  35.599998  26.400000  25.299999
2020-02-28  61.940578  34.529999  35.849998  25.600000  25.340000
2020-03-02  63.136536  35.430000  35.910000  26.110001  26.530001
2020-03-03  66.285889  35.029999  35.720001  25.120001  26.049999
2020-03-04  68.348915  36.180000  36.450001  24.809999  26.889999
2020-03-05  62.139904  35.090000  36.049999  20.650000  25.290001
2020-03-06  56.070423  32.349998  34.400002  21.049999  22.830000
2020-03-09  49.084045  27.549999  29.830000  17.379999  16.049999
2020-03-10  54.734940  31.680000  32.389999  18.320000  17.559999
2020-03-11  51.615486  29.010000  30.840000  15.650000  15.850000
2020-03-12  42.855106  23.719999  24.879999   9.970000  12.600000
2020-03-13  54.595413  28.070000  28.920000  11.170000  15.400000
2020-03-16  49.333202  23.510000  24.590000   8.040000  13.090000
2020-03-17  53.519051  24.250000  25.459999   7.780000  13.000000
2020-03-18  50.828152  19.520000  21.360001   5.600000  11.290000
2020-03-19  48.506001  17.400000  19.410000   6.250000  12.210000
2020-03-20  49.044182  16.809999  18.910000   7.280000  12.000000

In [21]:
# Calcula a varição diária de cada ação
# Calculate the daily variation of each stock

daily_variation_highests = (return_highests-return_highests.shift(1))/return_highests.shift(1)
daily_variation_highests

            AMER3.SA  ELET3.SA  ELET6.SA  GOLL4.SA  PETR4.SA
Date
2020-02-21       NaN       NaN       NaN       NaN       NaN
2020-02-26 -0.097306 -0.093202 -0.068965 -0.143111 -0.100549
2020-02-27 -0.045219 -0.019034 -0.037578 -0.089027 -0.034720
2020-02-28 -0.008930  0.030746  0.007022 -0.030303  0.001581
2020-03-02  0.019308  0.026064  0.001674  0.019922  0.046961
2020-03-03  0.049882 -0.011290 -0.005291 -0.037916 -0.018093
2020-03-04  0.031123  0.032829  0.020437 -0.012341  0.032246
2020-03-05 -0.090843 -0.030127 -0.010974 -0.167674 -0.059502
2020-03-06 -0.097674 -0.078085 -0.045770  0.019370 -0.097272
2020-03-09 -0.124600 -0.148377 -0.132849 -0.174347 -0.296978
2020-03-10  0.115127  0.149909  0.085820  0.054085  0.094081
2020-03-11 -0.056992 -0.084280 -0.047854 -0.145742 -0.097380
2020-03-12 -0.169724 -0.182351 -0.193256 -0.362939 -0.205047
2020-03-13  0.273954  0.183390  0.162379  0.120361  0.222222
2020-03-16 -0.096386 -0.162451 -0.149723 -0.280215 -0.150000
2020-03-17  0.084849  0.031476  0.035380 -0.032338 -0.006875
2020-03-18 -0.050279 -0.195052 -0.161037 -0.280206 -0.131538
2020-03-19 -0.045686 -0.108607 -0.091292  0.116071  0.081488
2020-03-20  0.011095 -0.033908 -0.025760  0.164800 -0.017199

In [22]:
# Calcula a variância das ações de menor coeficiente beta
# Calculates the variance of the smallest beta stocks

covariance_highests = daily_variation_highests.cov()

# Calcula a volatilidade das ações de menor beta
# Calculates the volatility of the smallest beta stocks

volatility_highests = np.sqrt(np.dot(weights.T,np.dot(covariance_highests,weights)))
volatility_highests

0.10377262870231922

# ---------------------------------------------------------------------------------------------------------------

 # Highests Beta Portfolio Return

In [23]:
# Seleciona as ações que farão parte dos portfolios simulados, neste caso são as ações que compõem o índice Bovespa
# Select the stocks that will be part of the simulated portfolios, in this case the stocks are part of the Bovespa Index

highests_beta_stocks = ['PETR3.SA','BBAS3.SA','GOLL4.SA','CSNA3.SA','PETR4.SA']

# Importa os dados do Yahoo Finance
# Import the data from Yahoo Finance

return_highests = yfin.download(highests_beta_stocks, start='2020-02-21', end="2020-03-21")['Close']
return_highests

[*********************100%***********************]  5 of 5 completed

             BBAS3.SA  CSNA3.SA   GOLL4.SA   PETR3.SA   PETR4.SA
Date
2020-02-21  49.220001     13.13  33.820000  30.850000  29.139999
2020-02-26  45.230000     11.70  28.980000  27.780001  26.209999
2020-02-27  45.790001     11.32  26.400000  26.830000  25.299999
2020-02-28  46.860001     11.18  25.600000  27.150000  25.340000
2020-03-02  47.150002     12.35  26.110001  28.100000  26.530001
2020-03-03  45.770000     12.17  25.120001  27.500000  26.049999
2020-03-04  45.820000     12.32  24.809999  28.219999  26.889999
2020-03-05  43.110001     11.95  20.650000  26.809999  25.290001
2020-03-06  42.299999     11.11  21.049999  24.059999  22.830000
2020-03-09  37.630001      8.30  17.379999  16.920000  16.049999
2020-03-10  39.610001      9.37  18.320000  18.360001  17.559999
2020-03-11  36.189999      8.02  15.650000  16.370001  15.850000
2020-03-12  31.250000      6.58   9.970000  12.920000  12.600000
2020-03-13  36.490002      7.95  11.170000  15.860000  15.400000
2020-03-16  30.400000      7.20   8.040000  13.130000  13.090000
2020-03-17  31.870001      7.75   7.780000  13.080000  13.000000
2020-03-18  26.610001      6.71   5.600000  11.050000  11.290000
2020-03-19  25.570000      6.36   6.250000  12.450000  12.210000
2020-03-20  24.600000      6.16   7.280000  12.220000  12.000000

In [24]:
# Obtém a variação total do valor das ações neste intervalo de tempo
# Gets the total variation of the stocks' value in this time interval

total_variation_highests = (return_highests.iloc[-1]-return_highests.iloc[0])/return_highests.iloc[0]
total_variation_highests

BBAS3.SA   -0.500203
CSNA3.SA   -0.530845
GOLL4.SA   -0.784743
PETR3.SA   -0.603890
PETR4.SA   -0.588195
dtype: float64

In [25]:
# Exibe a variação total do valor, os pesos das ações e seus tickets em uma tabela
# Displays total value variation, stock weights and their tickets in a table

portfolio_highests = pd.DataFrame({'Weight':weights,'Return':total_variation_highests})
portfolio_highests

          Weight    Return
BBAS3.SA     0.2 -0.500203
CSNA3.SA     0.2 -0.530845
GOLL4.SA     0.2 -0.784743
PETR3.SA     0.2 -0.603890
PETR4.SA     0.2 -0.588195

In [26]:
# Calcula o retorno médio das ações, ou seja, o retorno da carteira formada por elas
# Calculates the average return of the stocks (the return of the portfolio composted by them)

average_total_return_highests = total_variation_highests.mean()
average_total_return_highests

-0.6015752055281669

# Biggest Stocks Fall Period Final Result

In [27]:
final_results_total_return = [str(round(average_total_return_highests*100,2))+'%',str(round(average_total_return_lowests*100,2))+'%']
final_results_volatility = [round(volatility_highests,4),round(volatility_lowests,4)]

In [28]:
final_results = pd.DataFrame({'Total return':final_results_total_return,'Volatility':final_results_volatility},index=['Highests betas portfolio','Lowests betas portfolio'])
final_results

                         Total return  Volatility
Highests betas portfolio      -60.16%      0.1038
Lowests betas portfolio       -45.23%      0.0640

# ---------------------------------------------------------------------------------------------------------------

# Economic Recovery Period (21/03/2020 - 21/03/2021)

# ---------------------------------------------------------------------------------------------------------------

# Lowest Beta Portfolio Return

In [29]:
# Seleciona as ações que farão parte dos portfolios simulados, neste caso são as ações que compõem o índice Bovespa
# Select the stocks that will be part of the simulated portfolios, in this case the stocks are part of the Bovespa Index

# Importa os dados do Yahoo Finance
# Import the data from Yahoo Finance

return_lowests = yfin.download(lowests_beta_stocks, start='2020-03-21', end="2021-03-21")['Close']
return_lowests

[*********************100%***********************]  5 of 5 completed

             BRKM3.SA    IRBR3.SA  KLBN11.SA   PCAR3.SA   SUZB3.SA
Date
2020-03-23  13.860000  161.019440  13.510000  71.879997  28.799999
2020-03-24  15.050000  188.162720  13.470000  72.000000  28.900000
2020-03-25  16.650000  207.025009  13.880000  70.000000  29.350000
2020-03-26  18.440001  228.417587  14.130000  66.320000  28.049999
2020-03-27  18.750000  239.228897  14.980000  64.019997  32.869999
...               ...         ...        ...        ...        ...
2021-03-15  32.650002  150.096939  28.370001  25.000000  72.849998
2021-03-16  33.180000  150.843689  29.610001  24.690001  75.250000
2021-03-17  33.700001  153.332855  29.559999  24.900000  76.550003
2021-03-18  34.070000  153.581772  28.590000  25.000000  75.300003
2021-03-19  34.000000  153.830688  28.280001  28.309999  74.000000

[245 rows x 5 columns]

In [30]:
# Calcula a varição diária de cada ação
# Calculate the daily variation of each stock

daily_variation_lowests = (return_lowests-return_lowests.shift(1))/return_lowests.shift(1)
daily_variation_lowests

            BRKM3.SA  IRBR3.SA  KLBN11.SA  PCAR3.SA  SUZB3.SA
Date
2020-03-23       NaN       NaN        NaN       NaN       NaN
2020-03-24  0.085859  0.168571  -0.002961  0.001669  0.003472
2020-03-25  0.106312  0.100245   0.030438 -0.027778  0.015571
2020-03-26  0.107508  0.103333   0.018012 -0.052571 -0.044293
2020-03-27  0.016811  0.047331   0.060156 -0.034680  0.171836
...              ...       ...        ...       ...       ...
2021-03-15  0.016501 -0.025848  -0.035034  0.004016 -0.018855
2021-03-16  0.016233  0.004975   0.043708 -0.012400  0.032944
2021-03-17  0.015672  0.016502  -0.001689  0.008505  0.017276
2021-03-18  0.010979  0.001623  -0.032815  0.004016 -0.016329
2021-03-19 -0.002055  0.001621  -0.010843  0.132400 -0.017264

[245 rows x 5 columns]

In [31]:
# Obtém a variação total do valor das ações neste intervalo de tempo
# Gets the total variation of the stocks' value in this time interval

total_variation_lowests = (return_lowests.iloc[-1]-return_lowests.iloc[0])/return_lowests.iloc[0]
total_variation_lowests

BRKM3.SA     1.453103
IRBR3.SA    -0.044645
KLBN11.SA    1.093264
PCAR3.SA    -0.606149
SUZB3.SA     1.569445
dtype: float64

In [32]:
# Calcula o retorno médio das ações, ou seja, o retorno da carteira formada por elas
# Calculates the average return of the stocks (the return of the portfolio composted by them)

average_total_return_lowests = total_variation_lowests.mean()
average_total_return_lowests

0.6930033845068241

# ---------------------------------------------------------------------------------------------------------------

# Lowest Beta Portfolio Volatility

In [33]:
# Transforma a lista 'weights' em um vetor numpy
# Turns the list 'weights' into a numpy array

weights = np.asarray(weights)

In [34]:
# Calcula a variância das ações de menor coeficiente beta
# Calculates the variance of the smallest beta stocks

covariance_lowests = daily_variation_lowests.cov()

# Calcula a volatilidade das ações de menor beta
# Calculates the volatility of the smallest beta stocks

volatility_lowests = np.sqrt(np.dot(weights.T,np.dot(covariance_lowests,weights)))
volatility_lowests

0.026745530485309692

In [35]:
# Exibe a variação total do valor, os pesos das ações e seus tickets em uma tabela
# Displays total value variation, stock weights and their tickets in a table

portfolio_lowests = pd.DataFrame({'Weights':weights,'Returns':total_variation_lowests})
portfolio_lowests

           Weights   Returns
BRKM3.SA       0.2  1.453103
IRBR3.SA       0.2 -0.044645
KLBN11.SA      0.2  1.093264
PCAR3.SA       0.2 -0.606149
SUZB3.SA       0.2  1.569445

# ---------------------------------------------------------------------------------------------------------------

# Highest Beta Portfolio Return

In [36]:
# Seleciona as ações que farão parte dos portfolios simulados, neste caso são as ações que compõem o índice Bovespa
# Select the stocks that will be part of the simulated portfolios, in this case the stocks are part of the Bovespa Index

# Importa os dados do Yahoo Finance
# Import the data from Yahoo Finance

return_highests = yfin.download(highests_beta_stocks, start='2020-03-21', end="2021-03-21")['Close']
return_highests

[*********************100%***********************]  5 of 5 completed

             BBAS3.SA   CSNA3.SA   GOLL4.SA   PETR3.SA   PETR4.SA
Date
2020-03-23  22.129999   5.800000   6.930000  11.620000  11.500000
2020-03-24  25.920000   5.800000   8.100000  13.470000  13.250000
2020-03-25  29.030001   6.550000  10.940000  14.550000  14.320000
2020-03-26  30.490000   7.100000  13.040000  14.600000  14.390000
2020-03-27  28.240000   6.770000  12.590000  13.030000  13.300000
...               ...        ...        ...        ...        ...
2021-03-15  29.790001  35.830002  24.070000  23.260000  23.650000
2021-03-16  29.870001  36.950001  22.540001  22.910000  23.280001
2021-03-17  30.700001  37.639999  23.100000  23.639999  24.080000
2021-03-18  30.440001  37.040001  21.360001  22.969999  23.240000
2021-03-19  30.700001  35.610001  21.490000  23.520000  24.000000

[245 rows x 5 columns]

In [37]:
# Calcula a variação diária do preço das ações
# Calcules the daily variation of the stocks price

daily_variation_highests = (return_highests-return_highests.shift(1))/return_highests.shift(1)
daily_variation_highests

            BBAS3.SA  CSNA3.SA  GOLL4.SA  PETR3.SA  PETR4.SA
Date
2020-03-23       NaN       NaN       NaN       NaN       NaN
2020-03-24  0.171261  0.000000  0.168831  0.159208  0.152174
2020-03-25  0.119985  0.129310  0.350617  0.080178  0.080755
2020-03-26  0.050293  0.083969  0.191956  0.003436  0.004888
2020-03-27 -0.073795 -0.046479 -0.034509 -0.107534 -0.075747
...              ...       ...       ...       ...       ...
2021-03-15 -0.007000 -0.047581  0.056629  0.024670  0.020716
2021-03-16  0.002685  0.031259 -0.063565 -0.015047 -0.015645
2021-03-17  0.027787  0.018674  0.024845  0.031864  0.034364
2021-03-18 -0.008469 -0.015940 -0.075325 -0.028342 -0.034884
2021-03-19  0.008541 -0.038607  0.006086  0.023944  0.032702

[245 rows x 5 columns]

In [38]:
# Calcula a variação total do preço das ações durante o periodo de tempo estudado
# Calcules the total variation of the stocks price during the studied time period

total_variation_highests = (return_highests.iloc[-1]-return_highests.iloc[0])/return_highests.iloc[0]
total_variation_highests

BBAS3.SA    0.387257
CSNA3.SA    5.139655
GOLL4.SA    2.101010
PETR3.SA    1.024096
PETR4.SA    1.086957
dtype: float64

In [39]:
# Calcula o retorno médio das ações, ou seja, o retorno da carteira formada por elas
# Calculates the average return of the stocks (the return of the portfolio composted by them)

average_total_return_highests = total_variation_highests.mean()
average_total_return_highests

1.947795078253849

# ---------------------------------------------------------------------------------------------------------------

# Highest Beta Portfolio Volatility

In [40]:
# Calcula a covariância das ações de maior beta
# Calcules the covariance of the biggest beta stocks

covariance_highests = daily_variation_highests.cov()

# Calcula a volatilidade da carteira composta pelas ações maior beta
# Calcules the volatility of the portfolio composted by the biggest beta stocks

volatility_highests = np.sqrt(np.dot(weights.T,np.dot(covariance_highests,weights)))
volatility_highests

0.031210116537317804

In [41]:
# Exibe a variação total do valor, os pesos das ações e seus tickets em uma tabela
# Displays total value variation, stock weights and their tickets in a table

portfolio_highests = pd.DataFrame({'Weights':weights,'Returns':total_variation_highests})
portfolio_highests

          Weights   Returns
BBAS3.SA      0.2  0.387257
CSNA3.SA      0.2  5.139655
GOLL4.SA      0.2  2.101010
PETR3.SA      0.2  1.024096
PETR4.SA      0.2  1.086957

# ---------------------------------------------------------------------------------------------------------------

# Economic Recovery Period Final Result

In [42]:
final_results_total_return = [str(round(average_total_return_highests*100,2))+'%',str(round(average_total_return_lowests*100,2))+'%']
final_results_volatility = [round(volatility_highests,4),round(volatility_lowests,4)]

In [43]:
final_results = pd.DataFrame({'Total return':final_results_total_return,'Volatility':final_results_volatility},index=['Highests betas portfolio','Lowests betas portfolio'])
final_results

                         Total return  Volatility
Highests betas portfolio      194.78%      0.0312
Lowests betas portfolio         69.3%      0.0267